{% set version = "0.13.2" %}

package:
  name: geopandas
  version: {{ version }}

source:
  url: https://github.com/geopandas/geopandas/releases/download/v{{ version }}/geopandas-{{ version }}.tar.gz
  sha256: e5b56d9c20800c77bcc0c914db3f27447a37b23b2cd892be543f5001a694a968

build:
  number: 0
  noarch: python

outputs:
  - name: geopandas-base
    script: build_base.sh
    build:
      noarch: python
    requirements:
      build:
        - python                                 # [build_platform != target_platform]
        - cross-python_{{ target_platform }}     # [build_platform != target_platform]
      host:
        - python >=3.8
        - pip
      run:
        - python >=3.8
        - pandas >=1.1.0
        - shapely >=1.7.1
        - pyproj >=3.0.1
        - packaging

    test:
      imports:
        - geopandas
        - geopandas.io
      files:
        - test_data

  - name: geopandas
    requirements:
      host:
        - python >=3.8
      run:
        - python >=3.8
        - {{ pin_subpackage('geopandas-base', exact=True) }}
        - fiona
        - rtree
        - matplotlib-base
        - mapclassify >=2.4.0
        - folium
        - xyzservices

    test:
      imports:
        - geopandas
        - geopandas.io
      files:
        - test_data

about:
  home: http://geopandas.org
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: Geographic pandas extensions

extra:
  recipe-maintainers:
    - ocefpaf
    - jorisvandenbossche
    - jdmcbr
    - martinfleis
