{% set version = "0.12.0" %}

package:
  name: geopandas
  version: {{ version }}

source:
  url: https://github.com/geopandas/geopandas/releases/download/v{{ version }}/geopandas-{{ version }}.tar.gz
  sha256: 1980a5de8b3bc5a5e7db216f021c275bdf7b87c55400834baa65eadb88693925

build:
  number: 0
  noarch: python

outputs:
  - name: geopandas-base
    script: build_base.sh
    build:
      noarch: python
    requirements:
      build:
        - python                                 # [build_platform != target_platform]
        - cross-python_{{ target_platform }}     # [build_platform != target_platform]
      host:
        - python >=3.8
        - pip
      run:
        - python >=3.8
        - pandas >=1.0.5
        - shapely >=1.7, <2
        - pyproj >=2.6.1.post1
        - packaging

    test:
      imports:
        - geopandas
        - geopandas.io
      files:
        - test_data

  - name: geopandas
    requirements:
      host:
        - python >=3.8
      run:
        - python >=3.8
        - {{ pin_subpackage('geopandas-base', exact=True) }}
        - fiona
        - rtree
        - matplotlib-base
        - mapclassify >=2.4.0
        - folium
        - xyzservices

    test:
      imports:
        - geopandas
        - geopandas.io
      files:
        - test_data

about:
  home: http://geopandas.org
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: Geographic pandas extensions

extra:
  recipe-maintainers:
    - ocefpaf
    - jorisvandenbossche
    - jdmcbr
    - martinfleis
